-- MySQL Script generated by MySQL Workbench
-- Sat Aug 20 09:48:20 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Cidade`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Cidade` (
  `CidadeId` INT NOT NULL AUTO_INCREMENT,
  `NomeCidade` VARCHAR(80) NOT NULL,
  `Estado` CHAR(2) NULL,
  PRIMARY KEY (`CidadeId`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Cadastro`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Cadastro` (
  `CadastroId` INT NOT NULL AUTO_INCREMENT,
  `Nome` VARCHAR(80) NOT NULL,
  `TipoCadastro` CHAR(1) NULL,
  `Cpf` VARCHAR(18) NULL,
  `NumeroTelefone` VARCHAR(15) NULL,
  `NumeroCelular` VARCHAR(15) NULL,
  `NumeroCep` VARCHAR(9) NULL,
  `CidadeId` INT NULL,
  `NumeroEndereco` DECIMAL(5,0) NULL,
  `Endereco` VARCHAR(80) NULL,
  `BairroEndereco` VARCHAR(50) NULL,
  `Complemento` VARCHAR(80) NULL,
  `Mensalista` CHAR(1) NULL,
  PRIMARY KEY (`CadastroId`),
  INDEX `FK20_idx` (`CidadeId` ASC),
  UNIQUE INDEX `Cpf_UNIQUE` (`Cpf` ASC),
  CONSTRAINT `FK20`
    FOREIGN KEY (`CidadeId`)
    REFERENCES `mydb`.`Cidade` (`CidadeId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `mydb`.`Permissao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Permissao` (
  `PermissaoId` INT NOT NULL,
  `Descricao` VARCHAR(80) NULL,
  PRIMARY KEY (`PermissaoId`))
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `mydb`.`Empresa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Empresa` (
  `EmpresaId` INT NOT NULL AUTO_INCREMENT,
  `Nome` VARCHAR(80) NOT NULL,
  `RazaoSocial` VARCHAR(100) NULL,
  `CpfCnpj` VARCHAR(18) NULL,
  `TipoEmpresa` CHAR(1) NULL,
  `Endereco` VARCHAR(80) NULL,
  `NumeroEndereco` DECIMAL(5,0) NULL,
  `Complemento` VARCHAR(45) NULL,
  `NumeroCep` VARCHAR(9) NULL,
  `CidadeId` INT NULL,
  `BairroEndereco` VARCHAR(80) NULL,
  `UrlLogo` VARCHAR(255) NULL,
  `NumeroVagas` DECIMAL(5,0) NOT NULL,
  `Sobre` VARCHAR(255) NULL,
  `NumeroTelefone1` VARCHAR(15) NULL,
  `NumeroTelefone2` VARCHAR(15) NULL,
  `Email` VARCHAR(80) NULL,
  PRIMARY KEY (`EmpresaId`),
  INDEX `FK11_idx` (`CidadeId` ASC),
  UNIQUE INDEX `Cnpj_UNIQUE` (`CpfCnpj` ASC),
  CONSTRAINT `FK11`
    FOREIGN KEY (`CidadeId`)
    REFERENCES `mydb`.`Cidade` (`CidadeId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`DiasAtendimento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`DiasAtendimento` (
  `DiasAtendimentoId` INT NOT NULL AUTO_INCREMENT,
  `DescricaoDiasAtendimento` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`DiasAtendimentoId`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Estacionamento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Estacionamento` (
  `EstacionamentoId` INT NOT NULL AUTO_INCREMENT,
  `NomeEstacionamento` VARCHAR(100) NULL,
  `CpfCnpj` VARCHAR(18) NULL,
  `Endereco` VARCHAR(80) NULL,
  `NumeroEndereco` DECIMAL(5,0) NULL,
  `Complemento` VARCHAR(45) NULL,
  `NumeroCep` VARCHAR(9) NULL,
  `CidadeId` INT NULL,
  `BairroEndereco` VARCHAR(80) NULL,
  `NumeroVagas` DECIMAL(5,0) NOT NULL,
  `Sobre` VARCHAR(255) NULL,
  `NumeroTelefone1` VARCHAR(15) NULL,
  `NumeroTelefone2` VARCHAR(15) NULL,
  `Email` VARCHAR(80) NULL,
  `DiasAtendimentoId` INT NULL,
  `precoLivre` DECIMAL(18,2) NULL,
  `PrecoHora` DECIMAL(18,2) NULL,
  `EmpresaId` INT NOT NULL,
  `DataCadastro` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`EstacionamentoId`),
  INDEX `FK14_idx` (`DiasAtendimentoId` ASC),
  INDEX `FK23_idx` (`EmpresaId` ASC),
  INDEX `FK30_idx` (`CidadeId` ASC),
  CONSTRAINT `FK14`
    FOREIGN KEY (`DiasAtendimentoId`)
    REFERENCES `mydb`.`DiasAtendimento` (`DiasAtendimentoId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK23`
    FOREIGN KEY (`EmpresaId`)
    REFERENCES `mydb`.`Empresa` (`EmpresaId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK30`
    FOREIGN KEY (`CidadeId`)
    REFERENCES `mydb`.`Cidade` (`CidadeId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `mydb`.`Login`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Login` (
  `LoginId` INT NOT NULL AUTO_INCREMENT,
  `Email` VARCHAR(80) NULL,
  `NomeUsuario` VARCHAR(50) NULL,
  `Senha` VARCHAR(255) NULL,
  `CadastroId` INT NULL,
  `EstacionamentoId` INT NULL,
  `PermissaoId` INT NOT NULL,
  `TokenEmail` VARCHAR(255) NULL,
  PRIMARY KEY (`LoginId`),
  INDEX `FK10_idx` (`CadastroId` ASC),
  INDEX `FK16_idx` (`EstacionamentoId` ASC),
  UNIQUE INDEX `Email_UNIQUE` (`Email` ASC),
  UNIQUE INDEX `NomeUsuario_UNIQUE` (`NomeUsuario` ASC),
  UNIQUE INDEX `CadastroId_UNIQUE` (`CadastroId` ASC),
  INDEX `FK21_idx` (`PermissaoId` ASC),
  CONSTRAINT `FK10`
    FOREIGN KEY (`CadastroId`)
    REFERENCES `mydb`.`Cadastro` (`CadastroId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK16`
    FOREIGN KEY (`EstacionamentoId`)
    REFERENCES `mydb`.`Estacionamento` (`EstacionamentoId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK21`
    FOREIGN KEY (`PermissaoId`)
    REFERENCES `mydb`.`Permissao` (`PermissaoId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`FotoEstacionamento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`FotoEstacionamento` (
  `FotoEstacionamentoId` INT NOT NULL AUTO_INCREMENT,
  `EstacionamentoId` INT NOT NULL,
  `UrlFoto` VARCHAR(255) NULL,
  PRIMARY KEY (`FotoEstacionamentoId`),
  INDEX `FK12_idx` (`EstacionamentoId` ASC),
  CONSTRAINT `FK12`
    FOREIGN KEY (`EstacionamentoId`)
    REFERENCES `mydb`.`Estacionamento` (`EstacionamentoId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`FormaPagamento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`FormaPagamento` (
  `FormaPagamentoId` INT NOT NULL AUTO_INCREMENT,
  `Descricao` VARCHAR(80) NOT NULL,
  PRIMARY KEY (`FormaPagamentoId`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Receber`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Receber` (
  `ReceberId` INT NOT NULL AUTO_INCREMENT,
  `FormaPagamentoId` INT NOT NULL,
  `CadastroId` INT NOT NULL,
  `FluxoVagaId` INT NULL,
  `Valor` DECIMAL(18,2) NOT NULL,
  PRIMARY KEY (`ReceberId`),
  INDEX `FK13_idx` (`FormaPagamentoId` ASC) ,
  INDEX `FK22_idx` (`CadastroId` ASC),
  CONSTRAINT `FK13`
    FOREIGN KEY (`FormaPagamentoId`)
    REFERENCES `mydb`.`FormaPagamento` (`FormaPagamentoId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK22`
    FOREIGN KEY (`CadastroId`)
    REFERENCES `mydb`.`Cadastro` (`CadastroId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`FluxoVaga`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`FluxoVaga` (
  `FluxoVagaId` INT NOT NULL AUTO_INCREMENT,
  `DataEntrada` DATE NOT NULL,
  `DataSaida` DATE NULL,
  `HoraEntrada` TIME NOT NULL,
  `HoraSaida` TIME NULL,
  `CadastroId` INT NOT NULL,
  `PlacaVeiculo` VARCHAR(30) NOT NULL,
  `Observacao` VARCHAR(255) NULL,
  `EstacionamentoId` INT NOT NULL,
  `Reserva` CHAR(1) NOT NULL,
  PRIMARY KEY (`FluxoVagaId`),
  INDEX `FK15_idx` (`CadastroId` ASC),
  INDEX `FK24_idx` (`EstacionamentoId` ASC),
  CONSTRAINT `FK15`
    FOREIGN KEY (`CadastroId`)
    REFERENCES `mydb`.`Cadastro` (`CadastroId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK24`
    FOREIGN KEY (`EstacionamentoId`)
    REFERENCES `mydb`.`Estacionamento` (`EstacionamentoId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

------------------------------------------------ 22/09  ---------------------------------------------

ALTER TABLE `mydb`.`Empresa` DROP COLUMN NumeroVagas;
ALTER TABLE `mydb`.`Login` ADD Status CHAR(1) DEFAULT 'A' NOT NULL;

------------------------------------------------ 23/09  ---------------------------------------------

ALTER TABLE `mydb`.`Fluxovaga` CHANGE `CadastroId` `CadastroId` INT(11) NULL;
ALTER TABLE `mydb`.`Receber` CHANGE `CadastroId` `CadastroId` INT(11) NULL;

------------------------------------------------ 24/09  --------------------------------------------

CREATE TABLE IF NOT EXISTS `mydb`.`Carteira` (
  `CarteiraId` INT NOT NULL AUTO_INCREMENT,
  `CadastroId` INT NULL,
  `EmpresaId` INT NULL,
  `NumeroCartao` VARCHAR(50) NULL,
  `NomeCartao` VARCHAR(100) NULL,
  `DataExpiracaoCartao` CHAR(6) NULL,
  `CodigoSegurancaoCartao` CHAR(3) NULL,
  `CodigoPix` VARCHAR(255) NULL,
  `Status` ENUM('A','I') NOT NULL DEFAULT 'A' COMMENT 'A => Ativo, I => Inativo que seria também excluido, pois não será excluido nada dessa tabela',
  PRIMARY KEY (`CarteiraId`),
  INDEX `FK27_idx` (`CadastroId` ASC) ,
  INDEX `FK28_idx` (`EmpresaId` ASC) ,
  INDEX `FK25_idx` (`CarteiraId` ASC),
  CONSTRAINT `FK25`
    FOREIGN KEY (`CadastroId`)
    REFERENCES `mydb`.`Cadastro` (`CadastroId`),
  CONSTRAINT `FK26`
    FOREIGN KEY (`EmpresaId`)
    REFERENCES `mydb`.`Empresa` (`EmpresaId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE TABLE IF NOT EXISTS `mydb`.`Reserva` (
  `ReservaId` INT NOT NULL AUTO_INCREMENT,
  `DataEntrada` DATE NOT NULL,
  `DataSaida` DATE NULL,
  `HoraEntrada` TIME NOT NULL,
  `HoraSaida` TIME NULL,
  `CadastroId` INT NOT NULL,
  `Observacao` VARCHAR(255) NULL,
  `EstacionamentoId` INT NOT NULL,
  PRIMARY KEY (`ReservaId`),
  INDEX `FK29_idx` (`ReservaId` ASC),
  INDEX `FK30_idx` (`EstacionamentoId` ASC),
  CONSTRAINT `FK31`
    FOREIGN KEY (`EstacionamentoId`)
    REFERENCES `mydb`.`Estacionamento` (`EstacionamentoId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


ALTER TABLE `mydb`.`Receber` ADD CarteiraId INT NULL;
ALTER TABLE `mydb`.`Receber` ADD CONSTRAINT FK_Receber_CarteiraId FOREIGN KEY (CarteiraId) REFERENCES Carteira(CarteiraId);

ALTER TABLE `mydb`.`Receber` ADD EmpresaId INT NULL COMMENT 'Pagamento da empresa pelo Software';
ALTER TABLE `mydb`.`Receber` ADD CONSTRAINT FK_Receber_EmpresaId FOREIGN KEY (EmpresaId) REFERENCES Empresa(EmpresaId);

ALTER TABLE `mydb`.`Receber` ADD ReservaId INT NULL;
ALTER TABLE `mydb`.`Receber` ADD CONSTRAINT FK_Receber_ReservaId FOREIGN KEY (ReservaId) REFERENCES Reserva(ReservaId);

ALTER TABLE `mydb`.`Receber` ADD MesAno CHAR(6) NULL COMMENT 'Pagamento da empresa pelo Software';
ALTER TABLE `mydb`.`Receber` ADD Status ENUM('A','P','F') NOT NULL COMMENT 'A=>Aguardando Pagamento,P=>Processando Pagamento,F=>Finalizado';

ALTER TABLE `mydb`.`FluxoVaga` ADD ReservaId INT NULL;
ALTER TABLE `mydb`.`FluxoVaga` ADD CONSTRAINT FK_FluxoVaga_ReservaId FOREIGN KEY (ReservaId) REFERENCES Reserva(ReservaId);

ALTER TABLE `mydb`.`FluxoVaga` DROP COLUMN Reserva;

------------------------------------------------ 25/09  --------------------------------------------

ALTER TABLE `mydb`.`FluxoVaga` ADD Status ENUM('E','F') NOT NULL DEFAULT 'E' COMMENT 'E=>Em Andamento,F=>Finalizado';
UPDATE `mydb`.`FluxoVaga` SET Status = 'F';