-- MySQL Script generated by MySQL Workbench
-- Sat Aug 20 09:48:20 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Cidade`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Cidade` (
  `CidadeId` INT NOT NULL AUTO_INCREMENT,
  `NomeCidade` VARCHAR(80) NOT NULL,
  `Estado` CHAR(2) NULL,
  PRIMARY KEY (`CidadeId`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Cadastro`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Cadastro` (
  `CadastroId` INT NOT NULL AUTO_INCREMENT,
  `Nome` VARCHAR(80) NOT NULL,
  `TipoCadastro` CHAR(1) NULL,
  `Cpf` VARCHAR(18) NULL,
  `NumeroTelefone` VARCHAR(15) NULL,
  `NumeroCelular` VARCHAR(15) NULL,
  `NumeroCep` VARCHAR(9) NULL,
  `CidadeId` INT NULL,
  `NumeroEndereco` DECIMAL(5,0) NULL,
  `Endereco` VARCHAR(80) NULL,
  `BairroEndereco` VARCHAR(50) NULL,
  `Complemento` VARCHAR(80) NULL,
  `Mensalista` CHAR(1) NULL,
  PRIMARY KEY (`CadastroId`),
  INDEX `FK20_idx` (`CidadeId` ASC),
  UNIQUE INDEX `Cpf_UNIQUE` (`Cpf` ASC),
  CONSTRAINT `FK20`
    FOREIGN KEY (`CidadeId`)
    REFERENCES `mydb`.`Cidade` (`CidadeId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `mydb`.`Permissao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Permissao` (
  `PermissaoId` INT NOT NULL,
  `Descricao` VARCHAR(80) NULL,
  PRIMARY KEY (`PermissaoId`))
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `mydb`.`Empresa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Empresa` (
  `EmpresaId` INT NOT NULL AUTO_INCREMENT,
  `Nome` VARCHAR(80) NOT NULL,
  `RazaoSocial` VARCHAR(100) NULL,
  `CpfCnpj` VARCHAR(18) NULL,
  `TipoEmpresa` CHAR(1) NULL,
  `Endereco` VARCHAR(80) NULL,
  `NumeroEndereco` DECIMAL(5,0) NULL,
  `Complemento` VARCHAR(45) NULL,
  `NumeroCep` VARCHAR(9) NULL,
  `CidadeId` INT NULL,
  `BairroEndereco` VARCHAR(80) NULL,
  `UrlLogo` VARCHAR(255) NULL,
  `Sobre` VARCHAR(255) NULL,
  `NumeroTelefone1` VARCHAR(15) NULL,
  `NumeroTelefone2` VARCHAR(15) NULL,
  `Email` VARCHAR(80) NULL,
  `DataCadastro` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`EmpresaId`),
  INDEX `FK11_idx` (`CidadeId` ASC),
  UNIQUE INDEX `Cnpj_UNIQUE` (`CpfCnpj` ASC),
  CONSTRAINT `FK11`
    FOREIGN KEY (`CidadeId`)
    REFERENCES `mydb`.`Cidade` (`CidadeId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`DiasAtendimento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`DiasAtendimento` (
  `DiasAtendimentoId` INT NOT NULL AUTO_INCREMENT,
  `DescricaoDiasAtendimento` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`DiasAtendimentoId`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Estacionamento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Estacionamento` (
  `EstacionamentoId` INT NOT NULL AUTO_INCREMENT,
  `NomeEstacionamento` VARCHAR(100) NULL,
  `CpfCnpj` VARCHAR(18) NULL,
  `Endereco` VARCHAR(80) NULL,
  `NumeroEndereco` DECIMAL(5,0) NULL,
  `Complemento` VARCHAR(45) NULL,
  `NumeroCep` VARCHAR(9) NULL,
  `CidadeId` INT NULL,
  `BairroEndereco` VARCHAR(80) NULL,
  `NumeroVagas` DECIMAL(5,0) NOT NULL,
  `Sobre` VARCHAR(255) NULL,
  `NumeroTelefone1` VARCHAR(15) NULL,
  `NumeroTelefone2` VARCHAR(15) NULL,
  `Email` VARCHAR(80) NULL,
  `DiasAtendimentoId` INT NULL,
  `precoLivre` DECIMAL(18,2) NULL,
  `PrecoHora` DECIMAL(18,2) NULL,
  `EmpresaId` INT NOT NULL,
  `DataCadastro` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`EstacionamentoId`),
  INDEX `FK14_idx` (`DiasAtendimentoId` ASC),
  INDEX `FK23_idx` (`EmpresaId` ASC),
  INDEX `FK30_idx` (`CidadeId` ASC),
  CONSTRAINT `FK14`
    FOREIGN KEY (`DiasAtendimentoId`)
    REFERENCES `mydb`.`DiasAtendimento` (`DiasAtendimentoId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK23`
    FOREIGN KEY (`EmpresaId`)
    REFERENCES `mydb`.`Empresa` (`EmpresaId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK30`
    FOREIGN KEY (`CidadeId`)
    REFERENCES `mydb`.`Cidade` (`CidadeId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `mydb`.`Login`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Login` (
  `LoginId` INT NOT NULL AUTO_INCREMENT,
  `Email` VARCHAR(80) NULL,
  `NomeUsuario` VARCHAR(50) NULL,
  `Senha` VARCHAR(255) NULL,
  `CadastroId` INT NULL,
  `EstacionamentoId` INT NULL,
  `PermissaoId` INT NOT NULL,
  `TokenEmail` VARCHAR(255) NULL,
  `Status` CHAR(1) DEFAULT 'A' NOT NULL,
  PRIMARY KEY (`LoginId`),
  INDEX `FK10_idx` (`CadastroId` ASC),
  INDEX `FK16_idx` (`EstacionamentoId` ASC),
  UNIQUE INDEX `Email_UNIQUE` (`Email` ASC),
  UNIQUE INDEX `NomeUsuario_UNIQUE` (`NomeUsuario` ASC),
  UNIQUE INDEX `CadastroId_UNIQUE` (`CadastroId` ASC),
  INDEX `FK21_idx` (`PermissaoId` ASC),
  CONSTRAINT `FK10`
    FOREIGN KEY (`CadastroId`)
    REFERENCES `mydb`.`Cadastro` (`CadastroId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK16`
    FOREIGN KEY (`EstacionamentoId`)
    REFERENCES `mydb`.`Estacionamento` (`EstacionamentoId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK21`
    FOREIGN KEY (`PermissaoId`)
    REFERENCES `mydb`.`Permissao` (`PermissaoId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`FotoEstacionamento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`FotoEstacionamento` (
  `FotoEstacionamentoId` INT NOT NULL AUTO_INCREMENT,
  `EstacionamentoId` INT NOT NULL,
  `UrlFoto` VARCHAR(255) NULL,
  PRIMARY KEY (`FotoEstacionamentoId`),
  INDEX `FK12_idx` (`EstacionamentoId` ASC),
  CONSTRAINT `FK12`
    FOREIGN KEY (`EstacionamentoId`)
    REFERENCES `mydb`.`Estacionamento` (`EstacionamentoId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`FormaPagamento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`FormaPagamento` (
  `FormaPagamentoId` INT NOT NULL AUTO_INCREMENT,
  `Descricao` VARCHAR(80) NOT NULL,
  PRIMARY KEY (`FormaPagamentoId`))
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `mydb`.`Carteira`
-- -----------------------------------------------------

CREATE TABLE IF NOT EXISTS `mydb`.`Carteira` (
  `CarteiraId` INT NOT NULL AUTO_INCREMENT,
  `CadastroId` INT NULL,
  `EmpresaId` INT NULL,
  `TipoCartao` CHAR(1) NULL COMMENT 'D=>Débito,C=>Crédito, se tivel nullo não é cartão',
  `NumeroCartao` VARCHAR(50) NULL,
  `NomeCartao` VARCHAR(100) NULL,
  `DataExpiracaoCartao` CHAR(6) NULL,
  `CodigoSegurancaoCartao` CHAR(3) NULL,
  `CodigoPix` VARCHAR(255) NULL,
  `Status` ENUM('A','I') NOT NULL DEFAULT 'A' COMMENT 'A => Ativo, I => Inativo que seria também excluido, pois não será excluido nada dessa tabela',
  PRIMARY KEY (`CarteiraId`),
  INDEX `FK27_idx` (`CadastroId` ASC) ,
  INDEX `FK28_idx` (`EmpresaId` ASC) ,
  INDEX `FK25_idx` (`CarteiraId` ASC),
  CONSTRAINT `FK25`
    FOREIGN KEY (`CadastroId`)
    REFERENCES `mydb`.`Cadastro` (`CadastroId`),
  CONSTRAINT `FK26`
    FOREIGN KEY (`EmpresaId`)
    REFERENCES `mydb`.`Empresa` (`EmpresaId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `mydb`.`Reserva`
-- -----------------------------------------------------

CREATE TABLE IF NOT EXISTS `mydb`.`Reserva` (
  `ReservaId` INT NOT NULL AUTO_INCREMENT,
  `DataEntrada` DATE NOT NULL,
  `DataSaida` DATE NULL,
  `HoraEntrada` TIME NOT NULL,
  `HoraSaida` TIME NULL,
  `CadastroId` INT NOT NULL,
  `Observacao` VARCHAR(255) NULL,
  `EstacionamentoId` INT NOT NULL,
  PRIMARY KEY (`ReservaId`),
  INDEX `FK29_idx` (`ReservaId` ASC),
  INDEX `FK30_idx` (`EstacionamentoId` ASC),
  CONSTRAINT `FK31`
    FOREIGN KEY (`EstacionamentoId`)
    REFERENCES `mydb`.`Estacionamento` (`EstacionamentoId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `mydb`.`FluxoVaga`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`FluxoVaga` (
  `FluxoVagaId` INT NOT NULL AUTO_INCREMENT,
  `DataEntrada` DATE NOT NULL,
  `DataSaida` DATE NULL,
  `HoraEntrada` TIME NOT NULL,
  `HoraSaida` TIME NULL,
  `CadastroId` INT NULL,
  `PlacaVeiculo` VARCHAR(30) NOT NULL,
  `Observacao` VARCHAR(255) NULL,
  `EstacionamentoId` INT NOT NULL,
  `ReservaId` INT NULL,
  `Status` ENUM('E','F') NOT NULL DEFAULT 'E' COMMENT 'E=>Em Andamento,F=>Finalizado',
  PRIMARY KEY (`FluxoVagaId`),
  INDEX `FK15_idx` (`CadastroId` ASC),
  INDEX `FK24_idx` (`EstacionamentoId` ASC),
  CONSTRAINT `FK15`
    FOREIGN KEY (`CadastroId`)
    REFERENCES `mydb`.`Cadastro` (`CadastroId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK24`
    FOREIGN KEY (`EstacionamentoId`)
    REFERENCES `mydb`.`Estacionamento` (`EstacionamentoId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK39`
    FOREIGN KEY (`ReservaId`)
    REFERENCES `mydb`.`Reserva` (`ReservaId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `mydb`.`Receber`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Receber` (
  `ReceberId` INT NOT NULL AUTO_INCREMENT,
  `FormaPagamentoId` INT NOT NULL,
  `CadastroId` INT NULL,
  `FluxoVagaId` INT NULL,
  `ReservaId` INT NULL,
  `CarteiraId` INT NULL,
  `Valor` DECIMAL(18,2) NOT NULL,
  `Status` ENUM('A','P','R','F') NOT NULL COMMENT 'A=>Aguardando Pagamento,P=>Processando Pagamento,R=>Recusado,F=>Finalizado',
  PRIMARY KEY (`ReceberId`),
  INDEX `FK13_idx` (`FormaPagamentoId` ASC) ,
  INDEX `FK22_idx` (`CadastroId` ASC),
  INDEX `FK35_idx` (`FluxoVagaId` ASC),
  INDEX `FK36_idx` (`ReservaId` ASC),
  INDEX `FK37_idx` (`CarteiraId` ASC),
  CONSTRAINT `FK13`
    FOREIGN KEY (`FormaPagamentoId`)
    REFERENCES `mydb`.`FormaPagamento` (`FormaPagamentoId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK22`
    FOREIGN KEY (`CadastroId`)
    REFERENCES `mydb`.`Cadastro` (`CadastroId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK35`
    FOREIGN KEY (`FluxoVagaId`)
    REFERENCES `mydb`.`FluxoVaga` (`FluxoVagaId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK36`
    FOREIGN KEY (`ReservaId`)
    REFERENCES `mydb`.`Reserva` (`ReservaId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK37`
    FOREIGN KEY (`CarteiraId`)
    REFERENCES `mydb`.`Carteira` (`CarteiraId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `mydb`.`ReceberEmpresa`
-- -----------------------------------------------------

CREATE TABLE IF NOT EXISTS `mydb`.`ReceberEmpresa` (
  `ReceberEmpresaId` INT NOT NULL AUTO_INCREMENT,
  `FormaPagamentoId` INT NOT NULL,
  `EmpresaId` INT NOT NULL,
  `CarteiraId` INT NULL,
  `Valor` DECIMAL(18,2) NOT NULL,
  `DataPagamento` DATE NOT NULL,
  `DataVencimento` DATE NOT NULL,
  `Status` ENUM('A','P','R','F') NOT NULL COMMENT 'A=>Aguardando Pagamento,P=>Processando Pagamento,R=>Recusado,F=>Finalizado',
  PRIMARY KEY (`ReceberEmpresaId`),
  INDEX `FK32_idx` (`FormaPagamentoId` ASC) ,
  INDEX `FK33_idx` (`EmpresaId` ASC),
  INDEX `FK34_idx` (`CarteiraId` ASC),
  CONSTRAINT `FK32`
    FOREIGN KEY (`FormaPagamentoId`)
    REFERENCES `mydb`.`FormaPagamento` (`FormaPagamentoId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK33`
    FOREIGN KEY (`EmpresaId`)
    REFERENCES `mydb`.`Empresa` (`EmpresaId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK34`
    FOREIGN KEY (`CarteiraId`)
    REFERENCES `mydb`.`Carteira` (`CarteiraId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- VIEW `mydb`.`view_pagamento_empresa`
-- -----------------------------------------------------

CREATE VIEW view_pagamento_empresa AS
SELECT 
	  a.EmpresaId
     ,IF((DATE_ADD(DataCadastro, INTERVAL 30 DAY)>=NOW()),'S','N') AS Experimental
     ,DATE_FORMAT((DATE_ADD(DataCadastro, INTERVAL 30 DAY)), '%d/%m/%Y %H:%i') AS VencExperimentalBr 
     ,DATE_FORMAT((DATE_ADD(DataCadastro, INTERVAL 30 DAY)), '%Y-%m-%d') AS VencExperimental
     ,(EXISTS(
         SELECT 1 
         FROM ReceberEmpresa AS b 
         WHERE b.EmpresaId = a.EmpresaId
         AND b.Status = 'F')) AS PagouAlgumaVez
     ,(SELECT b.DataPagamento
         FROM ReceberEmpresa AS b 
         WHERE b.EmpresaId = a.EmpresaId
         AND b.Status = 'F' 
         ORDER BY b.ReceberEmpresaId DESC
         LIMIT 1) AS UltPagamento
     ,(SELECT DATE_FORMAT(b.DataPagamento, '%d/%m/%Y') 
         FROM ReceberEmpresa AS b 
         WHERE b.EmpresaId = a.EmpresaId 
         AND b.Status = 'F'
         ORDER BY b.ReceberEmpresaId DESC
         LIMIT 1) AS UltPagamentoBr
     ,(SELECT b.DataVencimento
         FROM ReceberEmpresa AS b 
         WHERE b.EmpresaId = a.EmpresaId 
         AND b.Status = 'F'
         ORDER BY b.ReceberEmpresaId DESC
         LIMIT 1) AS VencUltPagamento
     ,(SELECT DATE_FORMAT(b.DataVencimento, '%d/%m/%Y')
         FROM ReceberEmpresa AS b 
         WHERE b.EmpresaId = a.EmpresaId 
         AND b.Status = 'F'
         ORDER BY b.ReceberEmpresaId DESC
         LIMIT 1) AS VencUltPagamentoBr
     ,DATE_FORMAT(NOW(), '%m/%Y') AS CompetenciaAtual
FROM Empresa AS a;

-- -----------------------------------------------------
-- FUNCTION `mydb`.`f_SituacaoEmpresa`
-- -----------------------------------------------------

CREATE DEFINER=`root`@`localhost` FUNCTION `f_SituacaoEmpresa`(
	`p_EmpresaId` INT,
	`p_ret` INT
)
RETURNS LONGTEXT
LANGUAGE SQL
NOT DETERMINISTIC
CONTAINS SQL
SQL SECURITY DEFINER
COMMENT ''
BEGIN

  
   DECLARE p_Experimental CHAR(1);
   DECLARE p_VencExperimental VARCHAR(100);
   DECLARE p_PagouAlgumaVez INT;
   DECLARE p_UltPagamento DATE;
   DECLARE p_UltPagamentoBr VARCHAR(100);
   DECLARE p_VencUltPagamento DATE;
   DECLARE p_VencUltPagamentoBr VARCHAR(100);
   DECLARE p_CompetenciaAtual CHAR(100);
   DECLARE p_Agora DATE;
   DECLARE ret VARCHAR(1);
   DECLARE msg VARCHAR(500);
   DECLARE retornar VARCHAR(500);
   SELECT 
			Experimental
			,VencExperimentalBr
			,PagouAlgumaVez 
			,UltPagamento
			,UltPagamentoBr
			,VencUltPagamento
			,VencUltPagamentoBr
			,CompetenciaAtual
			,DATE_FORMAT(NOW(), '%Y-%m-%d')
			INTO p_Experimental
					,p_VencExperimental
					,p_PagouAlgumaVez 
					,p_UltPagamento
					,p_UltPagamentoBr
					,p_VencUltPagamento
					,p_VencUltPagamentoBr
					,p_CompetenciaAtual
					,p_Agora
		FROM view_pagamento_empresa 
		WHERE EmpresaId = p_EmpresaId;
		
	IF p_Experimental = 'S' AND p_PagouAlgumaVez = 0 THEN
		SET msg = CONCAT('{ADM_OU_EMPRESA} empresa esta utilizando o software pelo período experimental com expiração em ',p_VencExperimental,'.<br>A partir dessa data a utilização do software somente ficará disponível mediante ao pagamento mensal.');
		SET  ret = '1';
	ELSE
		IF p_PagouAlgumaVez = 1 THEN
			IF p_VencUltPagamento < p_Agora THEN
				SET msg = CONCAT('O último pagamento venceu em ',p_UltPagamentoBr,'.<br>A utilização do software somente ficará disponível novamente mediante ao pagamento do mês atual.');
				SET ret = '4';
			ELSE
			   SET msg = CONCAT('{ADM_OU_EMPRESA} empresa está com os pagamentos do software em dia.<br>O próximo vencimento ocorrerá em ',p_VencUltPagamentoBr,'.<br>A partir dessa data a utilização do software somente ficará disponível mediante ao pagamento mensal.');
				SET ret = '2';
			END IF;
		ELSE
			SET msg = CONCAT('O período experimental expirou em ',p_VencExperimental,'.<br>A utilização do software somente ficará disponível mediante ao pagamento mensal.');
			SET ret = '3';
		END IF;
		
		
	END IF;
	
	IF p_ret=1 THEN SET retornar = ret; ELSE SET retornar = msg; END IF;
	
   RETURN retornar;
END
